version: "3"
services:
  my-app:
    build: ./app
    image: sample_flask_mysql:latest
    links:
      - db
    depends_on:
      - db
    ports:
      - "5000:5000"
    networks:
      - my_network

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    networks:
      - my_network

networks:
  my_network:
    driver: bridge